---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== LOAD BALANCING =====================

    - namespace: Loadbalancing
      name: ManagementMenu
      label: LB Management
      icon: carbon:load-balancer-global
      children:
        data:

          - namespace: Loadbalancing
            name: LTM
            label: F5 Local Traffic Manager
            kind: LoadbalancerLTM
            icon: carbon:load-balancer-classic

          - namespace: Loadbalancing
            name: F5Node
            label: F5 Nodes
            kind: F5networksNode
            icon: mdi:server-plus

          - namespace: Loadbalancing
            name: F5PoolMember
            label: F5 Pool Member
            kind: F5networksPoolMember
            icon: mdi:server-plus

          - namespace: Loadbalancing
            name: F5Pool
            label: F5 Pool
            kind: F5networksPool
            icon: carbon:load-balancer-pool

          - namespace: Loadbalancing
            name: F5Monitor
            label: F5 Monitor
            kind: F5networksMonitor
            icon: tabler:checkup-list