---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== LOAD BALANCING =====================

    - namespace: Loadbalancing
      name: ManagementMenu
      label: LB Management
      icon: carbon:load-balancer-global
      children:
        data:

          - namespace: Loadbalancing
            name: LTM
            label: F5 Local Traffic Manager
            kind: LoadbalancerLTM
            icon: carbon:load-balancer-classic

          - namespace: Loadbalancing
            name: F5VIP
            label: F5 VIPs
            kind: F5networksVIP
            icon: carbon:floating-ip

          - namespace: Loadbalancing
            name: F5Pool
            label: F5 Pool
            kind: F5networksPool
            icon: carbon:load-balancer-pool

          - namespace: Loadbalancing
            name: F5PoolMember
            label: F5 Pool Member
            kind: F5networksPoolMember
            icon: mdi:server-plus

          - namespace: Loadbalancing
            name: F5Node
            label: F5 Nodes
            kind: F5networksNode
            icon: clarity:rack-server-solid

          - namespace: Loadbalancing
            name: F5Monitors
            label: F5 Monitors
            icon: mdi:heart-pulse
            children:
              data:

              - namespace: Loadbalancing
                name: F5LDAPMonitor
                label: F5 LDAP Monitor
                kind: F5networksLDAPMonitor
                icon: mdi:heart-pulse

              - namespace: Loadbalancing
                name: F5HTTPMonitor
                label: F5 HTTP Monitor
                kind: F5networksHTTPMonitor
                icon: mdi:heart-pulse

              - namespace: Loadbalancing
                name: F5HTTPSMonitor
                label: F5 HTTPS Monitor
                kind: F5networksHTTPSMonitor
                icon: mdi:heart-pulse

              - namespace: Loadbalancing
                name: F5TCPMonitor
                label: F5 TCP Monitor
                kind: F5networksTCPMonitor
                icon: mdi:heart-pulse

              - namespace: Loadbalancing
                name: F5ICMPMonitor
                label: F5 ICMP Monitor
                kind: F5networksICMPMonitor
                icon: mdi:heart-pulse

              - namespace: Loadbalancing
                name: F5ExternalMonitor
                label: F5 External Monitor
                kind: F5networksExternalMonitor
                icon: mdi:heart-pulse